spring:
  application:
    name: sorting-algorithms

sorting:
  #implementation: INSERTION_SORT
  #implementation: BUBBLE_SORT
  #implementation: BUBBLE_SORT_EARLY_STOP
  #implementation: MERGE_SORT_SIMPLE
  #implementation: MERGE_SORT_ADVANCED,
  #implementation: QUICK_SORT
  implementation: COUNTING_SORT
